### ISSUE TITLE
Anyone else looking for a pair?

### ISSUE THREAD

**Issue by SantiagoRubioDev** [HPCE/hpce-2016-cw5#1]
If you are having trouble finding a pair just say so. I think it will be easier to find a pair here, than each of us emailing David Thomas.

**Comment by m8pple** [comment]
Yup, I think this is quite a good way of looking (I am currently ~1.5 working days behind real-time on e-mail...)

**Comment by Fabian9** [comment]
Hi, I am looking for a team partner. 
@spr13 Did you find a pair so far?

**Comment by andreamifsud** [comment]
Me too - anyone still free?

**Comment by Fabian9** [comment]
I am still free. 
@andreamifsud Shall we team up?

**Comment by andreamifsud** [comment]
@Fabian9 yeah sure

**Comment by Fabian9** [comment]
@andreamifsud  Great!

**Comment by SantiagoRubioDev** [comment]
Sorry for not mentioning, I teamed up with @rs6713

**Comment by plus44** [comment]
Anyone still looking for a pair?

**Comment by a-camuto** [comment]
I am @plus44

**Comment by plus44** [comment]
@ac4312 Great, let's team up?

**Comment by a-camuto** [comment]
@plus44 Yeah add me as a collaborator !

**Comment by kezhen-liu** [comment]
Tho quite dumb to ask this late, but anyone still missing a pair?
