### ISSUE TITLE
bin executables

### ISSUE THREAD

**Issue by SantiagoRubioDev** [HPCE/hpce-2016-cw5#16]
I read the spec and looked in the src files but I did not find any examples or indication of how to use the executable. We want to test our performance with bin/execute_puzzle but how do we use it?
What are the inputs of each program? Can we use a pipeline like in the previous coursework or do we save the output in a file?
I would really appreciate if someone could post an example using each program to test the julia puzzle implementation. And comparing the correctness of the custom implementation with the reference implementation.
Thanks in advance.

**Comment by m8pple** [comment]
If you run the programs without parameters they give minimal
help strings - `bin/run_puzzle` is the easiest, as it is self
contained. So:

```
bin/run_puzzle julia 100 1
```

will run the `julia` puzzle, with a problem size of 100, and a logging level of 1.

To see what the others do, try:

```
make serenity_now
```

then it will create some input files and alternately feed it
to the reference and user implementations. You should be
able to see the commands going passed, or you can see
the commands in the makefile.

**Comment by SantiagoRubioDev** [comment]
Thanks, sorry I missed that.
