### ISSUE TITLE
Multiple User Variants

### ISSUE THREAD

**Issue by narobertson42** [HPCE/hpce-2016-cw5#17]
Which files need to be changed to have multiple user implementations for a single problem. Eg user_logic_sim_v3_opencl.hpp?

**Comment by andreamifsud** [comment]
Did you manage to find out how?

**Comment by narobertson42** [comment]
Yes, you need to change the name of the class and add it to the registrar

**Comment by andreamifsud** [comment]
Yes I did so, but how do you select the new implementation then? When I write `bin/run_puzzle` I get an error - `terminate called after throwing an instance of std::runtime_error what(): PuzzleRegistrar::register - There is already a handler for logic_sim` I should be getting a list of all four puzzles.
How do you differentiate between the two user implementations when you call the function?
