### ISSUE TITLE
Parallel logic_sim

### ISSUE THREAD

**Issue by a-camuto** [HPCE/hpce-2016-cw5#21]
I've been trying to parallelise the for loop in the "next" function because it doesn't have any apparent loop carried dependencies. The output is correct for smaller scales, but as soon as the scale increases my output is completely off. Has anyone been having similar issues with logic_sim ?

**Comment by zhiyb** [comment]
What I found out:
In STL, `vector<bool>` is different than other types of vectors. It was implemented by using bitfields, to save memory space. Therefore it is not thread safe when modifying different elements.

**Comment by a-camuto** [comment]
Oh awesome thank you !
