### ISSUE TITLE
Prepend login to *.tar.gz in dt10_runs

### ISSUE THREAD

**Issue by eugenius1** [HPCE/hpce-2016-cw5#22]
Hi,

Problem:  
Merge conflicts when merging multiple remote repos. Your auto tests run with the same name for the tar.gz archives. When merging the repos together there is a conflict due to the names being exactly the same.

Solution:
prepend login to `*.tar.gz`
e.g `2016-11-19T08+0000.tar.gz` -> `my_login-2016-11-19T08+0000.tar.gz`

**Comment by m8pple** [comment]
Ah, that never occurred to me.

Good point, and good solution - I've modified the auto_run script.
