### ISSUE TITLE
No tests in 4 days

### ISSUE THREAD

**Issue by alino95** [HPCE/hpce-2016-cw5#25]
Is there an issue with our repo sync or no tests have been run? 

Thank you!

**Comment by jeremych1000** [comment]
There should've been one just now.

**Comment by alino95** [comment]
Can you see the plots or only the CSVs & logs?

**Comment by jeremych1000** [comment]
Only the tarball, no graphs.
![](https://camo.githubusercontent.com/6721dea89f4d5f4330ccb861a72aeed28c56ba13/687474703a2f2f6d756666662e696e2f692f6166643439302e706e67)

**Comment by alino95** [comment]
Also do you know what the columns of the CSV stand for?

**Comment by alino95** [comment]
Btw thank you @jeremych1000 for replying :)

**Comment by m8pple** [comment]
I kicked off the one on Sat morning, then had an automated one triggered
last night (Mon). I haven't checked if it's uploaded yet as I had teaching/meetings
yesterday + today. Hopefully I don't have an ec2 instance spinning away still.

Currently going through outstanding issues - I'll look into the graphs as I go through.

**Comment by m8pple** [comment]
It looks like the test hung for hours and the watchdog process
didn't kill it (due to an interaction between one of the implementations and
the test environment).

The graphs didn't go up due to a related reason (disk was full...). I'm doing
another full run now, with the log prefix as suggested.

**Comment by m8pple** [comment]
Meant to comment, not close as well.

To answer the other part:

The columns of the CSVs are simply:
- puzzle_name
- scale
- last puzzle time (execute only)
- total elapsed time (wallclock)

The elapsed time is mainly for me to track the time budget per person.
There is a soft limit during which the last puzzle can execute, then
a hard after which the test will get forcibly killed (e.g. if the implementation
has hung, or is going to take hours).

**Comment by m8pple** [comment]
Latest run is complete, and a random sampling shows graphs showing
up for those who have opted in. Woo!

**Comment by awai54st** [comment]
Hi,
Unfortunately my repository is showing neither the tarball nor the graph from last night... 
Could you please have a look and see what went wrong?
Thank you
Best, awai54st

**Comment by m8pple** [comment]
You had `puzzles.o` commited, which caused a conflict with the version
that I built.

I removed my copy, pulled, merged, and then pushed again manually.

**Comment by awai54st** [comment]
Thank you! I have received the graphs
