### ISSUE TITLE
librt not found on Mac OS

### ISSUE THREAD

**Issue by Szypicyn** [HPCE/hpce-2016-cw5#3]
Doing `make all` on a Mac returns `ld: library not found for -lrt`. After searching  [stackoverflow](http://stackoverflow.com/questions/1505402/library-not-found-for-lrt-with-qtcreator-mac-os) I tried commenting out `LDLIBS += -lrt`. 

Everything then compiles. But when running any of the puzzles e.g. `./bin/run_puzzle julia` I get `Segmentation fault: 11` , which would indicate that the code is trying to access memory which is not allocated. Is this related to `librt`?

I would prefer not to waste my AWS credits on fixing this on a different platform if possible.

**Comment by pm1113** [comment]
You need to call the command serenity_now. That will show you an example of how to run the program.
