### ISSUE TITLE
Will there be another test today and tomorrow?

### ISSUE THREAD

**Issue by narobertson42** [HPCE/hpce-2016-cw5#30]
Sadly Amazon still haven't responded to my request to use servers in North Virginia.

**Comment by m8pple** [comment]
I'll be doing one later today. Is it actually useful to have one tomorrow? It seems kind
of late to be able to do anything useful.

Do they not let you use GPUs at all, or are you only able to use them in limited places?

**Comment by narobertson42** [comment]
They do not let me use GPUs at all

**Comment by awai54st** [comment]
I think it would be useful to have another test tomorrow. (Actually if possible, I would hope for one test each day until deadline...) My lab partner and me have just got our request approved yesterday night, and we may be trying a lot of tests over the weekend. Performance benchmarks would be really useful...

Thank you

**Comment by narobertson42** [comment]
@awai54st It's due tomorrow. There is no weekend.

**Comment by awai54st** [comment]
Oh... okay... thanks... @nar213
