### ISSUE TITLE
Maximum scale for random walk?

### ISSUE THREAD

**Issue by awai54st** [HPCE/hpce-2016-cw5#31]
Hi,

May I ask what is the maximum scale you will require from us? At the moment me and my lab partner are trying on GPU and GPU memory is limited... So we wish to know the maximum scale we should expect.

Thank you

Best, awai54st

**Comment by m8pple** [comment]
I take a similar approach in the final perf tests as in the auto-tests (though
different scripts). So there is a time-budget (though a fair bit longer), and
then see how far it can get before running out of time.

The graph memory size scales as ~n^1.5, while the compute scales as n^2, so
my back of the envelope calculations were that you wouldn't run out of
memory n=400000 or so.

If you're trading off space for isolation (e.g. private arrays per work-item)
you may hit that point earlier. Something to try is to allow sharing of
arrays between work-items using atomics, or to not launch the entire
grid at once (send through batches from software).
