### ISSUE TITLE
Question about the magic number in step() at random walk puzzle

### ISSUE THREAD

**Issue by DominicCYK** [HPCE/hpce-2016-cw5#4]
In the reference execution function for random walk puzzle, the step function inside has hard coded two constant number 1664525 and 1013904223. Can someone please explain their meaning and their relationship with the original Mersenne Twister series? Thanks!

**Comment by m8pple** [comment]
I won't comment too much on this, as the goal is to be able to accelerate things even
without necessarily understanding _exactly_ what it does. Of course, understanding
helps, but in this instance you can just see it as part of the specification.

If anyone else wants to chime in, then feel free.

**Comment by jeremych1000** [comment]
[Seems like a easily implementable and relatively fast RNG generator?](https://en.wikipedia.org/wiki/Linear_congruential_generator#Parameters_in_common_use)

**Comment by m8pple** [comment]
Closing as I think everyone has seen it.
