### ISSUE TITLE
Altering Input Creation?

### ISSUE THREAD

**Issue by narobertson42** [HPCE/hpce-2016-cw5#7]
Are we allowed to override `CreateInput` in `user_<puzzle_name>_.hpp` ? Given you are only measuring the wall-clock execution time of `Execute`, surely it would make sense to build _helpful_ data structures in `CreateInput`

**Comment by m8pple** [comment]
I'm afraid not - if you need to build up structures, it should be charged to your account,
not the creators.

Each created puzzle follows the file-format for that puzzle, which is essentially an API. So
I won't be calling your CreateInput, I'll only be calling your Execute. So it would be a bit
like trying to add extra information into a jpeg file - yes, you can do it, but any jpegs you
get from anyone else won't contain that info.

Something to think about is how much time creating those data structures takes. Depending
on the problem size, does it always make sense?
